### ISSUE TITLE
Erro no entry point da aplicação

### ISSUE THREAD

**Issue by oliveiralex** [ulaecio/challenge-one#1]
Caro Ulaecio,

Infelizmente seu trabalho não foi aceito! 

Ao fazer o git clone do seu projeto, o mesmo está apresentando um erro na classe principal da aplicação (entry point). Mesmo assim eu tentei executar e está exibindo a seguinte mensagem (conforme imagem abaixo)

![Captura de tela de 2021-05-25 13-25-10](https://user-images.githubusercontent.com/2441741/119534236-0e08d480-bd5d-11eb-91a0-a571cfedc062.png)

Peço por gentileza que você verifique o seu projeto (faça o git clone) e verifique. Assim que você fizer os ajustes, peço que você envie novamente para que possamos corrigir.

Abraço e bons estudos

**Comment by ulaecio** [comment]
Feito Update de `ClientsApplication` para `ClientApplication`,  feito `git clone` e realizado teste e o mesmo funcionou normalmente, funcionou até mesmo antes de fazer as modificações. só lembrando que a pasta do projeto é `backend` , não `clients `Por gentileza Clica no menu superior Project e escolha a opção Clean... para realizar o build do projeto e recompilar as classes.
Verifica também no menu Project se a opção Build Automatically está marcada.
Por fim, verifica se sua classe está no pacote br.com.alura.forum dentro do src/main/java.
![image](https://user-images.githubusercontent.com/34926656/119586480-2ef41880-bda3-11eb-864b-556dc91ea71e.png)
